# Generated by Django 4.2 on 2023-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20200507_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_count',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
